#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <loadfile.h>
#include <libcdvd.h>
#include "../utils.h"
#include "ps2_utils.h"

PS2DeviceKey deviceKey;
bool deviceKeyLoaded = false;

void PS2Utils_extractDeviceKey(const char* path) {
    require(!deviceKeyLoaded);

    char* pos = strchr(path, ':');
    requireNotNull(pos);

    size_t length = pos - path;
    char* result = safeMalloc((length + 1) * sizeof(char));
    strncpy(result, path, length);
    result[length] = '\0';

    // The "result" is the device key as a string (example: "mass" or "host")
    deviceKey = (PS2DeviceKey) {
        .key = result,
        .usesISO9660 = strncmp(result, "cdrom", strlen("cdrom")) == 0,
    };

    deviceKeyLoaded = true;
}

// Loads the required IOP drivers based on the current device key
// For cdrom devices, this loads the CDVD filesystem modules so we can read from the disc
void PS2Utils_loadFSDrivers() {
    require(deviceKeyLoaded);

    if (deviceKey.usesISO9660) {
        fprintf(stderr, "PS2Utils: Loading CDVD drivers for device key '%s'\n", deviceKey.key);

        int ret;
        ret = SifLoadModule("rom0:CDVDMAN", 0, nullptr);
        if (0 > ret) {
            fprintf(stderr, "PS2Utils: Failed to load CDVDMAN: %d\n", ret);
            abort();
        }

        ret = SifLoadModule("rom0:CDVDFSV", 0, nullptr);
        if (0 > ret) {
            fprintf(stderr, "PS2Utils: Failed to load CDVDFSV: %d\n", ret);
            abort();
        }

        sceCdInit(SCECdINIT);
        fprintf(stderr, "PS2Utils: CDVD initialized\n");
    }
}

#ifdef GPROF_PROFILING
// Embedded USB mass storage IRX modules (generated by bin2c at build time, only in profiler builds)
extern unsigned char usbd_irx[];
extern unsigned int size_usbd_irx;
extern unsigned char bdm_irx[];
extern unsigned int size_bdm_irx;
extern unsigned char bdmfs_fatfs_irx[];
extern unsigned int size_bdmfs_fatfs_irx;
extern unsigned char usbmass_bd_irx[];
extern unsigned int size_usbmass_bd_irx;

void PS2Utils_loadMassStorageDrivers() {
    require(deviceKeyLoaded);

    fprintf(stderr, "PS2Utils: Loading USB mass storage drivers for gprof output...\n");

    int ret;
    ret = SifExecModuleBuffer(usbd_irx, size_usbd_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        fprintf(stderr, "PS2Utils: Failed to load usbd: %d\n", ret);
    }

    ret = SifExecModuleBuffer(bdm_irx, size_bdm_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        fprintf(stderr, "PS2Utils: Failed to load bdm: %d\n", ret);
    }

    ret = SifExecModuleBuffer(bdmfs_fatfs_irx, size_bdmfs_fatfs_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        fprintf(stderr, "PS2Utils: Failed to load bdmfs_fatfs: %d\n", ret);
    }

    ret = SifExecModuleBuffer(usbmass_bd_irx, size_usbmass_bd_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        fprintf(stderr, "PS2Utils: Failed to load usbmass_bd: %d\n", ret);
    }

    // Wait for USB device detection
    sleep(3);

    fprintf(stderr, "PS2Utils: USB mass storage drivers loaded\n");
}
#endif

static bool PS2Utils_isAbsoluteOrDevicePath(const char* path) {
    if (path == nullptr || path[0] == '\0') return true;
    if (path[0] == '/' || path[0] == '\\') return true;
    return strchr(path, ':') != nullptr;
}

static bool PS2Utils_shouldKeepRootForGameChange(const char* path) {
    if (path == nullptr) return true;

    // Boot/config files are always in the root of the boot device.
    if (strcmp(path, "BOOT.ELF") == 0 || strcmp(path, "SLUS_000.00") == 0 ||
        strcmp(path, "SYSTEM.CNF") == 0 || strcmp(path, "CONFIG.JSN") == 0 ||
        strcmp(path, "CFG.JSN") == 0 || strcmp(path, "ICON.ICO") == 0) {
        return true;
    }

    // Shared DELTARUNE music stays in the root mus/ folder.
    if (strncmp(path, "mus/", 4) == 0 || strncmp(path, "mus\\", 4) == 0) return true;

    // Save/config files are handled by CONFIG.JSN mappings/mc0, not by chapter scoping.
    if (strcmp(path, "config.ini") == 0 || strcmp(path, "dr.ini") == 0) return true;
    if (strncmp(path, "filec_", 6) == 0 || strncmp(path, "filech", 6) == 0) return true;

    return false;
}

static char* PS2Utils_normalizeActiveGameDir(void) {
    const char* active = getenv("BUTTERSCOTCH_PS2_ACTIVE_GAMEDIR");
    if (active == nullptr || active[0] == '\0') active = getenv("BUTTERSCOTCH_ACTIVE_BUNDLE_DIR");
    if (active == nullptr || active[0] == '\0') return nullptr;

    while (*active == '/' || *active == '\\') active++;
    if (active[0] == '.' && (active[1] == '/' || active[1] == '\\')) active += 2;

    size_t len = strlen(active);
    while (len > 0 && (active[len - 1] == '/' || active[len - 1] == '\\')) len--;
    if (len == 0) return nullptr;

    char* out = safeMalloc(len + 1);
    memcpy(out, active, len);
    out[len] = '\0';
    for (size_t i = 0; out[i] != '\0'; i++) {
        if (out[i] == '\\') out[i] = '/';
    }
    return out;
}

static char* PS2Utils_scopePathForGameChange(const char* path) {
    if (PS2Utils_isAbsoluteOrDevicePath(path)) return safeStrdup(path);
    if (PS2Utils_shouldKeepRootForGameChange(path)) return safeStrdup(path);

    // Already chapter-scoped.
    if (strncmp(path, "chapter", 7) == 0 || strncmp(path, "CHAPTER", 7) == 0) {
        return safeStrdup(path);
    }

    char* active = PS2Utils_normalizeActiveGameDir();
    if (active == nullptr) return safeStrdup(path);

    size_t len = strlen(active) + 1 + strlen(path) + 1;
    char* scoped = safeMalloc(len);
    snprintf(scoped, len, "%s/%s", active, path);
    free(active);

    fprintf(stderr, "PS2Utils: scoped device path '%s' -> '%s'\n", path, scoped);
    return scoped;
}

// Creates a path with the device key + path for the loaded device key.
// During in-process game_change, PS2 renderer/audio call this directly for
// generated assets (ATLAS.BIN, TEXTURES.BIN, SOUNDBNK.BIN, SOUNDS.BIN), bypassing
// FileSystem::resolvePath. Scope those paths here so Chapter 3 does not render
// with the chapter-select atlas/sound bank and black-screen.
// You need to free after using the path!
char* PS2Utils_createDevicePath(const char* path) {
    require(deviceKeyLoaded);

    char* effectivePath = PS2Utils_scopePathForGameChange(path);

    if (deviceKey.usesISO9660) {
        size_t len = strlen(deviceKey.key) + 3 + strlen(effectivePath) + 2 + 1;
        char* devicePath = safeMalloc(len);
        snprintf(devicePath, len, "%s:\\%s;1", deviceKey.key, effectivePath);
        free(effectivePath);
        return devicePath;
    } else {
        size_t len = strlen(deviceKey.key) + 1 + strlen(effectivePath) + 1;
        char* devicePath = safeMalloc(len);
        snprintf(devicePath, len, "%s:%s", deviceKey.key, effectivePath);
        free(effectivePath);
        return devicePath;
    }
}
